### ISSUE TITLE
Build failure on fresh clone, missing bindings for @swc/core

### ISSUE THREAD

**Issue by yourbuddyconner** [cognosisai/platform#5]
Error: 

```
2023-02-03T17:19:29.802Z [ERROR] asset workflow-bundle-77103bdc80074da32adc.js 698 KiB [emitted] [immutable] (name: main)
2023-02-03T17:19:29.802Z [ERROR] runtime modules 2.03 KiB 5 modules
2023-02-03T17:19:29.802Z [ERROR] modules by path ./node_modules/@temporalio/ 209 KiB
2023-02-03T17:19:29.802Z [ERROR]   modules by path ./node_modules/@temporalio/common/ 111 KiB 19 modules
2023-02-03T17:19:29.802Z [ERROR]   modules by path ./node_modules/@temporalio/workflow/ 95.2 KiB
2023-02-03T17:19:29.802Z [ERROR]     ./node_modules/@temporalio/workflow/lib/worker-interface.js 11.8 KiB [built] [code generated]
2023-02-03T17:19:29.802Z [ERROR]     ./node_modules/@temporalio/workflow/lib/alea.js 2.87 KiB [built] [code generated]
2023-02-03T17:19:29.803Z [ERROR]     + 11 modules
2023-02-03T17:19:29.803Z [ERROR]   ./node_modules/@temporalio/worker/lib/workflow-log-interceptor.js 2.25 KiB [built] [code generated]
2023-02-03T17:19:29.803Z [ERROR] modules by path ./src/ 581 bytes
2023-02-03T17:19:29.803Z [ERROR]   ./src/workflows-autogenerated-entrypoint.js 542 bytes [built] [code generated]
2023-02-03T17:19:29.803Z [ERROR]   ./src/workflows.ts 39 bytes [built] [code generated] [1 error]
2023-02-03T17:19:29.803Z [ERROR] __temporal_custom_payload_converter (ignored) 15 bytes [built] [code generated]
2023-02-03T17:19:29.803Z [ERROR] __temporal_custom_failure_converter (ignored) 15 bytes [built] [code generated]
2023-02-03T17:19:29.803Z [ERROR] ./node_modules/ms/index.js 2.95 KiB [built] [code generated]
2023-02-03T17:19:29.803Z [ERROR] 
2023-02-03T17:19:29.803Z [ERROR] ERROR in ./src/workflows.ts
2023-02-03T17:19:29.803Z [ERROR] Module build failed (from ./node_modules/swc-loader/src/index.js):
2023-02-03T17:19:29.803Z [ERROR] Error: Bindings not found.
2023-02-03T17:19:29.803Z [ERROR]     at Compiler.<anonymous> (/Users/connerswann/code/platform/node_modules/@swc/core/index.js:225:19)
2023-02-03T17:19:29.803Z [ERROR]     at Generator.next (<anonymous>)
2023-02-03T17:19:29.803Z [ERROR]     at /Users/connerswann/code/platform/node_modules/@swc/core/index.js:34:71
2023-02-03T17:19:29.803Z [ERROR]     at new Promise (<anonymous>)
2023-02-03T17:19:29.804Z [ERROR]     at __awaiter (/Users/connerswann/code/platform/node_modules/@swc/core/index.js:30:12)
2023-02-03T17:19:29.804Z [ERROR]     at Compiler.transform (/Users/connerswann/code/platform/node_modules/@swc/core/index.js:202:16)
2023-02-03T17:19:29.804Z [ERROR]     at Object.transform (/Users/connerswann/code/platform/node_modules/@swc/core/index.js:344:21)
2023-02-03T17:19:29.804Z [ERROR]     at Object.<anonymous> (/Users/connerswann/code/platform/node_modules/swc-loader/src/index.js:86:21)
2023-02-03T17:19:29.804Z [ERROR]  @ ./src/workflows-autogenerated-entrypoint.js
2023-02-03T17:19:29.804Z [ERROR] 
2023-02-03T17:19:29.804Z [ERROR] webpack 5.74.0 compiled with 1 error in 426 ms
Error: Webpack finished with errors, if you're unsure what went wrong, visit our troubleshooting page at https://docs.temporal.io/typescript/troubleshooting#webpack-errors
    at /Users/connerswann/code/platform/node_modules/@temporalio/worker/src/workflow/bundler.ts:267:17
    at finalCallback (/Users/connerswann/code/platform/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/connerswann/code/platform/node_modules/webpack/lib/Compiler.js:505:17
    at /Users/connerswann/code/platform/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/connerswann/code/platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/connerswann/code/platform/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.storeBuildDependencies (/Users/connerswann/code/platform/node_modules/webpack/lib/Cache.js:122:37)
    at /Users/connerswann/code/platform/node_modules/webpack/lib/Compiler.js:501:19
    at Hook.eval [as callAsync] (eval at create (/Users/connerswann/code/platform/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/connerswann/code/platform/node_modules/tapable/lib/Hook.js:18:14)
```

Fixed by: 

```
npm i @swc/core
```

**Comment by mbusigin** [comment]
Thank-you, Conner!
